version: '3'
services:
    mysql.instrument:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_INSTRUMENT_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${INSTRUMENT_PASSWORD:-S3cret}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${INSTRUMENT_DATABASE:-instrumentdb_test}'
            MYSQL_USER: '${INSTRUMENT_USERNAME:-citizix}'
            MYSQL_PASSWORD: '${INSTRUMENT_PASSWORD:-S3cret}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql-instrument:/var/lib/mysql'
        networks:
            - instrument
    mongodb.piece:
        image: mongo:5.0
        ports:
          - '${FORWARD_PIECE_PORT:-27017}:27017'
        volumes:
          - mongo-piece:/data/db
        environment:
          MONGO_INITDB_ROOT_USERNAME: '${PIECE_USERNAME:-citizix}'
          MONGO_INITDB_ROOT_PASSWORD: '${PIECE_PASSWORD:-S3cret}'
          MONGO_INITDB_DATABASE: '${PIECE_DB_NAME}'
        networks:
          - instrument
    mongodb.review:
        image: mongo:5.0
        ports:
          - '${FORWARD_REVIEW_PORT:-27018}:27017'
        volumes:
          - mongo-review:/data/db
        environment:
          MONGO_INITDB_ROOT_USERNAME: '${REVIEW_USERNAME:-citizix}'
          MONGO_INITDB_ROOT_PASSWORD: '${REVIEW_PASSWORD:-S3cret}'
          MONGO_INITDB_DATABASE: '${REVIEW_DB_NAME}'
        networks:
          - instrument
    mongodb.counter:
        image: mongo:5.0
        ports:
          - '${FORWARD_COUNTER_PORT:-27020}:27017'
        volumes:
          - mongo-counter:/data/db
        environment:
          MONGO_INITDB_ROOT_USERNAME: '${COUNTER_USERNAME:-citizix}'
          MONGO_INITDB_ROOT_PASSWORD: '${COUNTER_PASSWORD:-S3cret}'
          MONGO_INITDB_DATABASE: '${COUNTER_DB_NAME}'
        networks:
          - instrument
networks:
    instrument:
        driver: bridge
volumes:
    mysql-instrument:
        driver: local
    mongo-piece:
        driver: local
    mongo-review:
        driver: local
    mongo-counter:
        driver: local
