name: REVIEW API build, test and deliver container

on: 
  pull_request:
    branches: ["dev"]

jobs:
  test:
    runs-on: ubuntu-latest
    name: REVIEW API Java 17 build, test, deliver container
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
          cache: maven

      - name: Start MongoDB for integration test
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-username: citizix
          mongodb-password: S3cret
          mongodb-port: 27018
      
      - name: Build, test and package REVIEW API
        run: mvn -B package --file ./review_api/pom.xml